### ISSUE TITLE
When hit Enter on the dialog command window, nothing happens

### ISSUE THREAD

**Issue by akirasan** [VedantParanjape/KiBuzzard#3]
_**(move herer for more organized)**_

I partially got it working on Win10 KiCad ver. 5.1.9 by using your version and overwriting the files I found here: 
https://github.com/arturo182/KiBuzzard/commit/621c7ee9247106f22fd7e06f87db86707086a906
but when I hit Enter on the menu (after entering my text) nothing happens.
![KiBuzzard](https://user-images.githubusercontent.com/48794887/105062039-2a5fd200-5a48-11eb-9e81-0fc01dd71a06.png)

_Originally posted by @DCelectronics in https://github.com/VedantParanjape/KiBuzzard/issues/2#issuecomment-762954281_

**Comment by akirasan** [comment]
Is important to do the installation with command:

git clone https://github.com/VedantParanjape/KiBuzzard.git --recursive

If you download the code and unzip, the code of "buzzad" are not replicate. Check this directory:

![image](https://user-images.githubusercontent.com/3648643/105106557-692c7100-5ab6-11eb-9463-9754424cccea.png)

(README.md file)

**Comment by akirasan** [comment]
The label is create on 0,0 position. Check it, doing zoom out:
![image](https://user-images.githubusercontent.com/3648643/105107085-90d00900-5ab7-11eb-84c7-db0cfeb6786e.png)

![image](https://user-images.githubusercontent.com/3648643/105107142-b2c98b80-5ab7-11eb-932f-275a892688cb.png)

**Comment by iharshadec** [comment]
Does this work on Windows 10 - KiCad 5.1.9 as well? I am getting error while intalling requirements command.

**Comment by VedantParanjape** [comment]
@akirasan Thanks for this issue, would you mind sending a PR with these visual aids added in the Readme?

**Comment by VedantParanjape** [comment]
> Does this work on Windows 10 - KiCad 5.1.9 as well? I am getting error while intalling requirements command.

Hi please check dcelectronics's comment. As if now this won't work on windows out of box. I will try to add support in the coming few days.

**Comment by VedantParanjape** [comment]
> Is important to do the installation with command:
> 
> git clone https://github.com/VedantParanjape/KiBuzzard.git --recursive
> 
> If you download the code and unzip, the code of "buzzad" are not replicate. Check this directory:
> 
> ![image](https://user-images.githubusercontent.com/3648643/105106557-692c7100-5ab6-11eb-9463-9754424cccea.png)
> 
> (README.md file)

Yes, it is absolutely important to download the submodule.

**Comment by iharshadec** [comment]
Just tried this on linux as I was not able to get it working with Windows.
Linux 20 KiCad 5.1.9.
Copied KiBuzzard folder using command
```
$ cd ~/.kicad/scripting/plugins
$ git clone https://github.com/VedantParanjape/KiBuzzard.git --recursive
$ cd KiBuzzard
$ pip3 install -r requirements.txt --user
```

I got Icon on the Pcbnew but nothing is coming to 0,0 location as ENTER is not working at all when dilog box is open.

**Comment by VedantParanjape** [comment]
> Just tried this on linux as I was not able to get it working with Windows.
> Linux 20 KiCad 5.1.9.
> Copied KiBuzzard folder using command
> 
> ```
> $ cd ~/.kicad/scripting/plugins
> $ git clone https://github.com/VedantParanjape/KiBuzzard.git --recursive
> $ cd KiBuzzard
> $ pip3 install -r requirements.txt --user
> ```
> 
> I got Icon on the Pcbnew but nothing is coming to 0,0 location as ENTER is not working at all when dilog box is open.

can you run the kicad in terminal and try it ? error will be printed out in terminal

**Comment by iharshadec** [comment]
> > Just tried this on linux as I was not able to get it working with Windows.
> > Linux 20 KiCad 5.1.9.
> > Copied KiBuzzard folder using command
> > ```
> > $ cd ~/.kicad/scripting/plugins
> > $ git clone https://github.com/VedantParanjape/KiBuzzard.git --recursive
> > $ cd KiBuzzard
> > $ pip3 install -r requirements.txt --user
> > ```
> > 
> > 
> > I got Icon on the Pcbnew but nothing is coming to 0,0 location as ENTER is not working at all when dilog box is open.
> 
> can you run the kicad in terminal and try it ? error will be printed out in terminal

This is what I got in Terminal,

Traceback (most recent call last):
  File "/home/harshad/.kicad/scripting/plugins/KiBuzzard/KiBuzzard/dialog/dialog.py", line 21, in OnTextEnter
    self.func(self.m_textCtrl4.GetValue())
  File "/home/harshad/.kicad/scripting/plugins/KiBuzzard/KiBuzzard/__init__.py", line 148, in run_buzzard
    footprint.SetPosition(pcbnew.wxPoint(0, 0))
AttributeError: 'NoneType' object has no attribute 'SetPosition'

**Comment by VedantParanjape** [comment]
@iharshadec It's either a python issue

https://github.com/VedantParanjape/KiBuzzard/issues/1

check this issue, he had the exact same issue. solved by upgrading python

or you are giving a wrong buzzard command.

**Comment by iharshadec** [comment]
> @iharshadec It's either a python issue
> 
> #1
> 
> check this issue, he had the exact same issue. solved by upgrading python
> 
> or you are giving a wrong buzzard command.

I got this working after installing python-is-python3 package on ubuntu. Windows still does not working tried installing required packages manually but still not working on windows.

**Comment by VedantParanjape** [comment]
> > @iharshadec It's either a python issue
> > #1
> > check this issue, he had the exact same issue. solved by upgrading python
> > or you are giving a wrong buzzard command.
> 
> I got this working after installing python-is-python3 package on ubuntu. Windows still does not working tried installing required packages manually but still not working on windows.

/rant 

Windows OS should be packed in a rocket and thrown into space. Windows is absolutely useless for development, one needs to spend more time on setting up tools than actually develop something using that tool

/rant end

**Comment by dcelectr** [comment]
@VedantParanjape I totally agree with your rant regarding Windows used for development. 

I did not use the git command (I downloaded the files form the web interface, and I added the dependencies manually).
![Buzard_deps](https://user-images.githubusercontent.com/48794887/105621503-157f9780-5dd6-11eb-8fbf-9c05f4f3fa54.png)

I successfully added the requirements.
![pip3_install](https://user-images.githubusercontent.com/48794887/105621989-47dfc380-5ddb-11eb-82e1-837eb3126100.png)

I also added the path the the path in the Environment Variables.

Still, it does nothing after I type a text in the KiBuzzard window and hit Enter.

Lastly, I want to clarify something. I am not expecting anyone to give me a solution. I posted it here because it was a step moving forward with support on Windows.

**Comment by VedantParanjape** [comment]
> @VedantParanjape I totally agree with your rant regarding Windows used for development. 
> 
> I did not use the git command (I downloaded the files form the web interface, and I added the dependencies manually).
> ![Buzard_deps](https://user-images.githubusercontent.com/48794887/105621503-157f9780-5dd6-11eb-8fbf-9c05f4f3fa54.png)
> 
> I successfully added the requirements.
> ![pip3_install](https://user-images.githubusercontent.com/48794887/105621989-47dfc380-5ddb-11eb-82e1-837eb3126100.png)
> 
> I also added the path the the path in the Environment Variables.
> 
> Still, it does nothing after I type a text in the KiBuzzard window and hit Enter.
> 

I'm pretty sure this is kicad specific issue, I mean regarding python3/2 thing. Can you run kicad through terminal? then on using the plugin you'll see debug output in command line.

**Comment by dcelectr** [comment]
I believe it is a KiCad specific issue. On Windows I had installed only Python3, and I recently installed Python2 to support the plugins in version 5.1.9. So, I managed to make working a lot of the available plugins.  
In Windows 10, I cannot run KiCad through terminal.

**Comment by dcelectr** [comment]
I upgraded my KiCad version on Debian 10 (x86-64) from v5.0.2 to v5.1.9 (you may think that this was way overdue, but please respect my preference for stable releases:)

I cloned the KiBuzzard repository recursively, and I installed successfully the pip dependencies (Python 3.7) after I had to upgrade the pip install (just like I had to do in Windows 10). 

I added path .local/bin/ in my .bashrc (because I got a warning that f2py etc was not on PATH)

The KiBuzzard plug-in appears and the window to enter a text opens.  
When I type the text as pictured below and hit ENTER nothing happens.
![KiBuzzard](https://user-images.githubusercontent.com/48794887/106291110-381c1100-6219-11eb-9cc6-6acf0a37ad28.png)

I restarted KiCad from the terminal and opened the KiBuzzard window to enter my text as above, and below is the error message I get.

![Terminal](https://user-images.githubusercontent.com/48794887/106291268-6b5ea000-6219-11eb-861b-af4e6c556116.png)

On issue #1, it was posted "installed the package python-is-python3 fixed this issue" on Ubuntu 20.04. 

Debian 10 does not have such package, and I am reluctant to hack and break my stable Debian or make something else stop working.

I am sharing all these to help with identifying the root cause of the problem. If you have any suggested edits for the scripts, I would gladly try them out. Thank you.

**Comment by VedantParanjape** [comment]
@DCelectronics The root cause of this is kicad calling `python` and expecting it to be `python3`, but what it gets is `python2.7`.

To give a crux of the error message, the following line fails and return NaN object. It does so because kicad isn't able to run pcbnew.py

https://github.com/VedantParanjape/KiBuzzard/blob/0fd6c638058bc6068c921e3aec8e61eb8c63a50f/KiBuzzard/__init__.py#L141

Maybe try this https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3 ?

**Comment by dcelectr** [comment]
@VedantParanjape  Thank you for the suggestion, which was safe and reversible.

I tried it, confirmed that python points python3, and still I get the same error.
![alias_python](https://user-images.githubusercontent.com/48794887/106312466-acb07900-6234-11eb-8ac2-fa3a20e02352.png)

I also tired in a project with project specific footprints defined (KIPRJMOD) within the project.
Is there anything else in the scripts that I can change and try out?

All the other plug-ins (via stitching, circular keep-out, curved traces etc) are working fine, and I feel this one is getting close.

Another thing that I noticed is different in Linux from Windows is that the KiCad Python Scripting Console in Linux is using version 3.7 (even without alias python=python3) instead of 2.7 I saw in Windows.
![console](https://user-images.githubusercontent.com/48794887/106312479-b2a65a00-6234-11eb-837a-3cf336148738.png)

**Comment by VedantParanjape** [comment]
@DCelectronics We could try one thing, add this above the conflicting line and let me know the output.

```python
import sys
print (sys.version)
```

**Comment by dcelectr** [comment]
Sure thing, I added the two lines you suggested above the line 148 in the ../KiBuzzard/KiBuzzard/\__init\__py file, and this is what I get, highlighted with white background, which indicates python3 (and this is without: alias python=pyton3) .
![version](https://user-images.githubusercontent.com/48794887/106362642-f612ce00-62f1-11eb-93a9-8adf1c6d4630.png)

**Comment by VedantParanjape** [comment]
> Sure thing, I added the two lines you suggested above the line 148 in the ../KiBuzzard/KiBuzzard/\__init\__py file, and this is what I get, highlighted with white background, which indicates python3 (and this is without: alias python=pyton3) .
> ![version](https://user-images.githubusercontent.com/48794887/106362642-f612ce00-62f1-11eb-93a9-8adf1c6d4630.png)
> 
> 

This is insane, why won't this just work 🙄. Maybe greg davil can help? Can you create a issue there?

**Comment by gregdavill** [comment]
@VedantParanjape Probably easier just to tag me, since this issue is related to this code base.

KiCad 5 does not offer a mechanism for a plugin to initiate a "interactive placement". So when using that fork, the label is simply placed at 0,0 in the pcbnew canvas, so when you press "enter" nothing happening is the expected behavior. But we should also see a label in the upper right corner.
> The label is create on 0,0 position. Check it, doing zoom out:
> ![image](https://user-images.githubusercontent.com/3648643/105107085-90d00900-5ab7-11eb-84c7-db0cfeb6786e.png)
> 
> ![image](https://user-images.githubusercontent.com/3648643/105107142-b2c98b80-5ab7-11eb-932f-275a892688cb.png)


In KiCad 5.99 we are cheating a little, and using the system clipboard. But this actually works quite well, all things considered.
Have you been able to call buzzard directly to create a footprint. And then place that manually through the GUI?

With the error you've posted, I'm thinking that this call isn't loading the footprint, instead returning a `NoneType`:
https://github.com/VedantParanjape/KiBuzzard/blob/0fd6c638058bc6068c921e3aec8e61eb8c63a50f/KiBuzzard/__init__.py#L141

https://github.com/VedantParanjape/KiBuzzard/blob/0fd6c638058bc6068c921e3aec8e61eb8c63a50f/KiBuzzard/__init__.py#L129-L138

This section seems a bit suspect to me. Windows file paths and unix paths use different directory separators, here it's hard-coded as `/`

Can you confirm what the value of `filepath` and `self.buzzard_label_module_name` is? We need to ensure these are located in a directory you have permission to write in.

Probably no reason to place these footprints in `os.environ['KIPRJMOD']`, as this may be inside `Program Files` on windows and not directly modifiable by a user. It might be nicer to just use a folder in the temp directory instead, once the footprint is in the board layout this temp folder can be removed.

**Comment by dcelectr** [comment]
@gregdavill Thank you for your help with this.

The following is tested on Debian 10 KiCad v5.1.9.
The KIPRJMOD is inside the user home subdirectory.

![KIPRJMOD](https://user-images.githubusercontent.com/48794887/106407141-49c40b00-6409-11eb-8d51-2ee8f8f216e0.png)

I added ```print(filepath)``` in line 134 to see the value of the ```filepath```, and I got this (highlighted in the terminal screen capture):

![filepath](https://user-images.githubusercontent.com/48794887/106407146-4df02880-6409-11eb-8b12-f5c0c89aff5c.png)

I removed the ```+ "/"``` from lines 129 in the original code and added a ```print(self.buzzard_label_module_name)```  under line 135 to see the value of the ```self.buzzard_label_module_name```, and I got this:

![module_name](https://user-images.githubusercontent.com/48794887/106407282-aaebde80-6409-11eb-8662-9b957fb5f8cf.png)

Note that the double ```//``` is now ```/```

I also noticed that it created a folder ```./buzzard_labels.pretty/``` inside my project and an empty ```buzzard_labels.kicad_mod``` file.
This modification moved this forward, but it did not place anything at 0,0 location inside the Pcbnew.

![buzzard_mod](https://user-images.githubusercontent.com/48794887/106407508-38c7c980-640a-11eb-8f4d-a0c684f22c65.png)

**Comment by gregdavill** [comment]
Since `buzzard_labels.kicad_mod` is empty I suspect that's the real issue here.

From a terminal can you try running this:
```console
cd /home/user/.kicad_plugins/KiBuzzard/deps/buzzard
python buzzard.py "test" -o ki-5.1.x -stdout
```

Does that give you an error?

**Comment by dcelectr** [comment]
Yes, I get an ImportError. 

![error](https://user-images.githubusercontent.com/48794887/106411539-8563d280-6413-11eb-934f-7b3cb0ed9b73.png)

I confirmed that I have installed the svgpathtools inside the folder
/home/user/.local/lib/python3.7/site-packages/svgpathtools/

**Comment by gregdavill** [comment]
Can you try, this should try to fix up these import errors.

```console
$ python -m pip install -r requirements.txt --user
```

**Comment by dcelectr** [comment]
I have performed 
```~/.kicad_plugins/KiBuzzard/deps/buzzard$ python3 -m pip install -r requirements.txt --user```
and all requiments are satisfied.
When I enter
```~/.kicad_plugins/KiBuzzard/deps/buzzard$ python -m pip install -r requirements.txt --user```
I get"
```/usr/bin/python: No module named pip```

**Comment by gregdavill** [comment]
Ohh, right. Does this work?

```console
$ python3 buzzard.py "test" -o ki-5.1.x -stdout
```

**Comment by dcelectr** [comment]
It does!
```(module "buzzardLabel" (layer "F.Cu") (tedit "6017799")```
``` (attr virtual)```
``` (fp_poly (pts (xy 1.12 0.02) blah blah...```

**Comment by gregdavill** [comment]
The script runs `python` rather than `python3` (Since on my computer python is just an alias for python3.)

https://github.com/VedantParanjape/KiBuzzard/blob/888e2521546cc64c907bbee0e75aa1d11fc015db/KiBuzzard/__init__.py#L113

So that's likely your issue, try changing this to python3.

**Comment by dcelectr** [comment]
On my Linux, alias python=python3 did not work (I tried it before).

I modified line 113 inside ```KiBuzzard/KiBuzzard/__init__.py``` file to 
``` ['python3', buzzard_script] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)```
and it now **works** for the first time!

I will try the same fix on the Windows 10 and report if that works too for others who may be interested.

Thank you for your help!

**Comment by VedantParanjape** [comment]
Hi @gregdavill I couldn't tag you, maybe GitHub doesn't allow that.

The plugin does work on Ubuntu 20, but on other systems people are getting the above error due to python path.

I am using KPJRMOD path, as that is the project directory. I will changed it to /tmp. But won't this create a issue next time I try to open kicad after reboot ? the footprint will be missing. 

It seems @DCelectronics solved the issue, I will make the change in code.

**Comment by VedantParanjape** [comment]
> On my Linux, alias python=python3 did not work (I tried it before).
> 
> I modified line 113 inside ```KiBuzzard/KiBuzzard/\_\_init__.py``` file to 
> ``` ['python3', buzzard_script] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)```
> and it now **works** for the first time!
> 
> I will try the same fix on the Windows 10 and report if that works too for others who may be interested.
> 
> Thank you for your help!
> 
> 
> 

cool that it works now, can you send a PR with this change?

**Comment by dcelectr** [comment]
Thanks to @gregdavill for his help, I tired in the Windows 10 two changes:

I modified line 113 inside ```C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\__init__.py``` file to 
``` ['python3', buzzard_script] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)```

I modified line 22 inside ```C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\dialog\dialog_base.py``` file to 
``` self.SetSizeHints( wx.DefaultSize[0], wx.DefaultSize[1] )```

Now KiBuzzard works on Windows 10 for KiCad v5.1.9.

P.S. It does create a folder ```\buzzard_labels.pretty\``` inside my project with a```buzzard_labels.kicad_mod``` file inside.

**Comment by dcelectr** [comment]
> I am using KPJRMOD path, as that is the project directory. I will changed it to /tmp. But won't this create a issue next time I try to open kicad after reboot ? the footprint will be missing.

Keep in mind that the ```buzzard_labels.kicad_mod``` file gets overwritten every time you make a new buzzard label. It appears to me that the plug-in wants to write somwhere a footprint file before inserting it in the Pcbnew file. The Pcbnew file would always maintain the polygon parameters for each new buzzard label. I will investigate if I loose buzzard labels when I update footprints from the library AND have selected "delete unused footprints." I will also investigate if buzzard labels are modified to the last buzzard label after updating footprints from the library, because the .kicad_mod file is in the project defined path. I think having the buzzard footprint file in the /tmp folder would prevent overwriting all buzzard labels with the last one, because the footprint is not saved in a defined path.

**Comment by VedantParanjape** [comment]
> Thanks to @gregdavill for his help, I tired in the Windows 10 two changes:
> 
> I modified line 113 inside `C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\__init__.py` file to
> ` ['python3', buzzard_script] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`
> 
> I modified line 22 inside `C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\dialog\dialog_base.py` file to
> ` self.SetSizeHints( wx.DefaultSize[0], wx.DefaultSize[1] )`
> 
> Now KiBuzzard works on Windows 10 for KiCad v5.1.9.
> 
> P.S. I does create a folder `\buzzard_labels.pretty\` inside my project with a`buzzard_labels.kicad_mod` file inside.

That's cool, can you please send a PR with above changes ? I have created a new branch for it.

**Comment by VedantParanjape** [comment]
> Keep in mind that the `buzzard_labels.kicad_mod` file gets overwritten every time you make a new buzzard label. It appears to me that the plug-in wants to write somwhere a footprint file before inserting it in the Pcbnew file. The Pcbnew file would always maintain the polygon parameters for each new buzzard label. I will investigate if I loose buzzard labels when I update footprints from the library AND have selected "delete unused footprints." I will also investigate if buzzard labels are modified to the last buzzard label after updating footprints from the library, because the .kicad_mod file is in the project defined path. I think having the buzzard footprint file in the /tmp folder would prevent overwriting all buzzard labels with the last one, because the footprint is not saved in a defined path.

Yes, if you update the pcb from netlist, the footprint do get deleted if you select update option. I think the footprints are stored in the .kicad_mod files.

**Comment by dcelectr** [comment]
>That's cool, can you please send a PR with above changes ? I have created a new branch for it.

I will proceed with a PR after I fully test the changes. 
The modification of line 22 inside ```C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\dialog\dialog_base.py``` file to 
``` self.SetSizeHints( wx.DefaultSize[0], wx.DefaultSize[1] )``` was specific to Windows 10, and I have not tested it on Linux, yet. 

I also changed line 97 inside ```C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\__init__.py``` file  to ```) if 'pcbnew' in x.GetTitle().lower() and not 'python3' in x.GetTitle().lower()][0]``` for consistency.

I am exploring other enhancements. 

I like the idea from @gregdavill to store this buzzard in the TEMP or TMP location, and I am currently testing it.

For example I modified line 129 inside ```C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\__init__.py``` file  to ```filepath = os.environ['tmp'] + "/" + self.buzzard_label_library_path``` and now it stores the ```buzzard_labels.kicad_mod``` inside the Windows 10 user defined TMP folder. I would like to try this change on Linux as well.

I used ```'TMP'``` and ```'tmp'``` in Windows 10 and they both work by storing the buzzard footprint inside ```C:\Users\user\AppData\Local\Temp```. I decided to go with the lower case ```'tmp'``` to see if that works in Linux as well.

I discovered the following behavior:
By default, you cannot update buzzard footprints and overwrite them in the Pcbnew file, 

![Not_Updated_Footprints](https://user-images.githubusercontent.com/48794887/106486095-49665700-647f-11eb-9ecf-f9c73fb9be47.png)

**unless,** you have defined a path under your Project Specific Libraries as shown below.

![Proj_Specific_Lib_Path](https://user-images.githubusercontent.com/48794887/106486243-70bd2400-647f-11eb-90e2-c07dbbc2a582.png)

If the latter is true, your buzzard footprints would be overwritten with the last one.

![updated_footprints](https://user-images.githubusercontent.com/48794887/106486269-774b9b80-647f-11eb-9256-002cb4430439.png)

Also, buzzard footprints would be overwritten with the last one if you update the pcb from netlist, with the option **Update footprints** and without the option to **Delete extra footprints**, AND the path under your Project Specific Libraries is including the location of the buzzard footprint.

My conclusion is that we should put them in a TMP folder to prevent the risk of "updating" all buzzard footprints with the last one.

Finally, if you update the pcb from netlist, the footprint do get deleted only if you select **Delete extra footprints** option.

**Comment by VedantParanjape** [comment]
> Finally, if you update the pcb from netlist, the footprint do get deleted only if you select Delete extra footprints option.

Seems good enough then. As for making it windows compatible, can you check changes made by arturo to @gregdavill 's repository ?

Other than that, just use

```python
if os.some_function == "windows":
    do_this
elif os.some_function == "linux":
   do_that
```

**Comment by dcelectr** [comment]
>Seems good enough then. As for making it windows compatible, can you check changes made by arturo to @gregdavill 's repository ?

I did made it Windows compatible when I saidL
>Now KiBuzzard works on Windows 10 for KiCad v5.1.9.

@gregdavill repository has merged the changes from Arturo.

>The modification of line 22 inside ```C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\dialog\dialog_base.py``` file to 
``` self.SetSizeHints( wx.DefaultSize[0], wx.DefaultSize[1] )``` was specific to Windows 10, and I have not tested it on Linux, yet.

I tested it and it works in both Linux and Windows 10. 
For the time being I am not going to change anything regarding saving the buzzard footprint in /tmp folder.
So I am going to clone your repository, make the changes, and send you a PR.

I am trying to make the GUI work. The CMD portion is working (with a better text vertical alignment).

![WIP](https://user-images.githubusercontent.com/48794887/106505823-d5d04400-6496-11eb-95bf-0f0e399f250e.png)

The GUI is giving me errors, and I do not have the necessary Python to make it work.

![GUI_ERROR](https://user-images.githubusercontent.com/48794887/106505981-0adc9680-6497-11eb-9b2a-c31d25304e50.png)

**Comment by gregdavill** [comment]
My opinion is that these labels are generated only in pcbnew. And for v5 we have to save them and import them as a footprint. They get cached inside the pcbnew file, so the library is not needed once the label is placed.

An alternative is that we can label the footprint with a timestamp, and append it to a pcbnew footprint library. But I'm struggling to see the utility in that.

**Comment by dcelectr** [comment]
@gregdavill 
>They get cached inside the pcbnew file, so the library is not needed once the label is placed.

I agree 100%.

>But I'm struggling to see the utility in that.

Yeah, I don't see the value of saving these footprints, unless you save them in a global user defined library (with writing permissions) so you can routinely use them in other projects. However, generating them from scratch is not that much effort. 
Also, knowing how buzzard labels can potential be deleted from the Pcbnew file (via update footprints with delete extra footprints selected), it is good practice to save backup files.

I would like to make the GUI interface work as it makes it easier to set some of the parameters <> [] and generate the buzzard footprints in the same way the Command Line does it in v5.1.9.

**Comment by VedantParanjape** [comment]
@DCelectronics should I sync with changes on greg's repository ? It will be easier to merge with the main repo in future.

**Comment by VedantParanjape** [comment]
> > Seems good enough then. As for making it windows compatible, can you check changes made by arturo to @gregdavill 's repository ?
> 
> I did made it Windows compatible when I saidL
> 
> > Now KiBuzzard works on Windows 10 for KiCad v5.1.9.
> 
> @gregdavill repository has merged the changes from Arturo.

Yes, I know. I said so, because if changes made to make it work on windows were same as arturo's it will be easier to merge this repository with @gregdavill 's in future.

**Comment by VedantParanjape** [comment]
> > Seems good enough then. As for making it windows compatible, can you check changes made by arturo to @gregdavill 's repository ?
> 
> I did made it Windows compatible when I saidL
> 
> > Now KiBuzzard works on Windows 10 for KiCad v5.1.9.
> 
> @gregdavill repository has merged the changes from Arturo.
> 
> > The modification of line 22 inside `C:\Users\user\AppData\Roaming\kicad\scripting\plugins\KiBuzzard\KiBuzzard\dialog\dialog_base.py` file to
> > ` self.SetSizeHints( wx.DefaultSize[0], wx.DefaultSize[1] )` was specific to Windows 10, and I have not tested it on Linux, yet.
> 
> I tested it and it works in both Linux and Windows 10.
> For the time being I am not going to change anything regarding saving the buzzard footprint in /tmp folder.
> So I am going to clone your repository, make the changes, and send you a PR.
> 
> I am trying to make the GUI work. The CMD portion is working (with a better text vertical alignment).
> 
> ![WIP](https://user-images.githubusercontent.com/48794887/106505823-d5d04400-6496-11eb-95bf-0f0e399f250e.png)
> 
> The GUI is giving me errors, and I do not have the necessary Python to make it work.
> 
> ![GUI_ERROR](https://user-images.githubusercontent.com/48794887/106505981-0adc9680-6497-11eb-9b2a-c31d25304e50.png)

the GUI won't work, as by default it passes scale factor as 0, so buzzard fails miserably.

**Comment by dcelectr** [comment]
If you sync the changes from Greg's repository, I know that it would not work for sure. I have cherrypicked changes from Greg's repository and only the Command line is working (tested on Linux only at the moment)

**Comment by VedantParanjape** [comment]
> If you sync the changes from Greg's repository, I know that it would not work for sure. I have cherrypicked changes from Greg's repository and only the Command line is working (tested on Linux only at the moment)

Ohk, I won't sync.

check this: https://github.com/gregdavill/KiBuzzard/issues/13

There' s a issue with GUI code, the scale input box causes issue. If you set it to anything other than 0, it works.

Try out this branch: https://github.com/VedantParanjape/KiBuzzard/tree/wip-gui-change

**Comment by DCelectronics** [comment]
I will try it out tomorrow. It's 00:43 here💤

**Comment by VedantParanjape** [comment]
@DCelectronics https://github.com/gregdavill/KiBuzzard/issues/13#issuecomment-771726991 here's the fix

**Comment by VedantParanjape** [comment]
This is not in active development and changes have been merged into upstream, go to upstream repo. Closing the issue.
